name: Unit Tests

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - release/*
  workflow_call:
  workflow_dispatch: {}
jobs:
  unit:
    name: Unit Tests
    timeout-minutes: 20
    runs-on: ubuntu-latest
    env:
      PYX_API_KEY: ${{ secrets.PYX_READ_ONLY_KEY }}
    strategy:
      matrix:
        python_version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
    - uses: astral-sh/setup-uv@v6
      with:
        version: "0.8.17"
    - name: Setup
      run: |
        set -ex
        uv sync --group dev --group test --all-extras
    - name: Run Unit Tests
      run: |
        set -ex
        uv run pytest -m "not integration" --maxfail=10
  
