name: Integration Tests

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*
  workflow_dispatch: {}

jobs:
  integration:
    name: Integration Tests
    timeout-minutes: 40
    runs-on: LargeGithubRunner
    strategy:
      matrix:
        python_version: ["3.10"]
    env:
      PYX_API_KEY: ${{ secrets.PYX_READ_ONLY_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.17"
      - name: Setup
        run: |
          set -ex
          uv sync --group dev --group test --all-extras
      - name: Run Integration Tests
        run: |
          set -ex
          uv run pytest -m integration --run-integration --full-trace --timeout=180 --timeout-method=thread --tb=long --capture=tee-sys -vv --maxfail=10

